keepalive = 60

auth = "plain[passwd=/etc/ocserv/ocpasswd]"

compression = false

tls-priorities = "NORMAL:%SERVER_PRECEDENCE:%COMPAT:-RSA:-VERS-SSL3.0:-ARCFOUR-128:-VERS-TLS1.0:-VERS-TLS1.1"

socket-file = /run/ocserv-socket

tcp-port = 443
udp-port = 443

server-cert = /etc/ocserv/certs/tls.crt
server-key = /etc/ocserv/certs/tls.key

deny-roaming = false

predictable-ips = true

use-occtl = true

isolate-workers = true

try-mtu-discovery = true

device = ocserv

ipv4-network = 192.198.222.0
ipv4-netmask = 255.255.255.0

default-domain = cluster.local

route = 10.0.0.0/255.0.0.0

tunnel-all-dns = false
dns = 10.43.0.10
