---
apiVersion: v1
kind: Service
metadata:
  name: ocserv
  namespace: default
spec:
  ports:
  - name: https-tcp
    nodePort: 30340
    port: 443
  - name: https-udp
    nodePort: 30340
    port: 443
    protocol: UDP
  selector:
    app: ocserv
  type: NodePort
---
